projectname/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/single', 'HomeController@single');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('profiles', 'ProfileController');
Route::get('/postcategory', [
	'uses' => 'PostCategoryController@index',
	'as' => 'postcategory'
]);


Route::post('/postcategory/store', [
	'uses' => 'PostCategoryController@store',
	'as' => 'postcategory.store'
]);

Route::get('/postcategory/{postcategory}', [
	'uses' => 'PostCategoryController@show',
	'as' => 'postcategory.show'
]);

Route::resource('/posts', 'PostController');

projectname/app/Profile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    protected $fillable= ['name', 'email', 'date_of_birth', 'image', 'gender', 'address', 'user_id']; 

    public function user()
    {
    	return $this->belongsTo('App\User');
    }
}

projectname/app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Profile;
use Illuminate\Support\Facades\Auth;

class ProfileController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $profiles = Profile::orderBy('id', 'desc')->paginate(5);
        return view('profiles.index', compact('profiles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('profiles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:50|min:5',
            'email'=> 'required|email|unique:profiles',
            'date_of_birth' => 'required',
            'image' => 'required'
        ]);
        $input= $request->all();
        if(isset($input['image'])){
            $input['image'] = $this->upload($input['image']);
        }else{
            $input['image'] = 'img/default.jpg';
        }
        $input['user_id'] = Auth::user()->id;
        Profile::create($input);
        return redirect('profiles');
    }

    public function upload($file)
    {
        //$extension = $file->getClientOriginalExtension();
        $name = time().$file->getClientOriginalName();
        $filename = $name;
        $current = public_path('img/');
        $file->move($current, $filename);
        return 'img/'.$filename;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $profile = Profile::findOrFail($id);
        return view('profiles.show')->with('profile', $profile);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $profile = Profile::findOrFail($id);
        return view('profiles.edit')->with('profile', $profile);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $profile = Profile::findOrFail($id);
        $input = $request->all();
        if(isset($input['image'])){
            $input['image'] = $this->upload($input['image']);
        }
        $profile->update($input);
        return redirect('profiles');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Profile::find($id)->delete();
        return redirect()->back();
    }
}

projectname/resources/views/profiles/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-sm-8 col-sm-offset-2">
			@if(count($errors->all()) > 0)
			<div class="alert alert-warning">
				<ul>
					@foreach($errors->all() as $error)
						<li>{{$error}}</li>
					@endforeach
				</ul>
			</div>
			@endif
			<form action="{{route('profiles.store')}}" enctype="multipart/form-data" method="POST">
				{{csrf_field()}}
				<div class="form-group">
					<label for="name">Name</label>
					<input type="text" id="name" name="name" class="form-control">
				</div>
				<div class="form-group">
					<label for="email">Email</label>
					<input type="email" id="email" name="email" class="form-control">
				</div>
				<div class="form-group">
					<label for="date_of_birth">Date of Birth</label>
					<input type="date" id="date_of_birth" name="date_of_birth" class="form-control">
				</div>
				<div class="form-group">
					<label for="image">Select Your Profile Image</label>
					<input type="file" id="image" name="image" class="form-control">
				</div>
				<div class="form-group">
					<label for="gender">Select Your Gender</label>
					<input type="radio" name="gender" value="male"> Male
					<input type="radio" name="gender" value="female"> Female
					<input type="radio" name="gender" value="others"> Others
				</div>
				<div class="form-group">
					<label for="address">Address</label>
					<textarea name="address" id="address" class="form-control" cols="30" rows="5"></textarea>
				</div>
				<button type="submit" class="btn btn-primary">Create</button>
			</form>
		</div>
	</div>
</div>
@endsection
@section('scripts')

@endsection

projectname/resources/views/profiles/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-sm-7 col-sm-offset-2">
			<h3>Edit Profile</h3>
			<form action="{{route('profiles.update', $profile->id)}}" enctype="multipart/form-data" method="POST">
				{{csrf_field()}}
				{{method_field('PUT')}}
				<div class="form-group">
					<label for="name">Name</label>
					<input type="text" value="{{$profile->name}}" id="name" name="name" class="form-control">
				</div>
				<div class="form-group">
					<label for="email">Email</label>
					<input type="email" id="email" value="{{$profile->email}}" name="email" class="form-control">
				</div>
				<div class="form-group">
					<label for="date_of_birth">Date of Birth</label>
					<input type="date" id="date_of_birth" name="date_of_birth"  value="{{$profile->date_of_birth}}" class="form-control">
				</div>
				<div class="form-group">
					<label for="image">Select Your Profile Image</label>
					<input type="file" id="image" name="image" class="form-control">
				</div>
				<div class="form-group">
					<label for="gender">Select Your Gender</label>
					<input type="radio" name="gender" value="male" {{($profile->gender == 'male') ? 'checked' : ''}}> Male
					<input type="radio" name="gender" value="female" {{ ($profile->gender == 'female') ? 'checked' : ''}}> Female
					<input type="radio" name="gender" value="others" {{($profile->gender == 'others') ? 'checked' : ''}}> Others
				</div>
				<div class="form-group">
					<label for="address">Address</label>
					<textarea name="address" id="address" class="form-control" cols="30" rows="5">{{$profile->address}}</textarea>
				</div>
				<button type="submit" class="btn btn-primary">update</button>
			</form>
		</div>
		<div class="col-sm-3">
			<img src="{{asset($profile->image)}}" class="img-responsive" alt="">
		</div>
	</div>
</div>
@endsection
@section('scripts')

@endsection

projectname/resources/views/profiles/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<h1>Profile List <a href="{{url('profiles/create')}}" class="btn btn-success pull-right">Create</a></h1>
			<div class="col-sm-12">
				<table class="table table-bordered">
					<thead>
						<tr>
							<th>Id</th>
							<th>Name</th>
							<th>Email</th>
							<th>Birth Date</th>
							<th>Image</th>
							<th>Gender</th>
							<th>Address</th>
							<th>Created By</th>
							<th width="180">Action</th>
						</tr>
					</thead>
					<tbody>
						<div style="display: none">{{$i= 1}}</div>
						@foreach($profiles as $profile)

						<tr>
							<td>{{ $i++ }}</td>
							<td>{{$profile->name}}</td>
							<td>{{$profile->email}}</td>
							<td>{{$profile->date_of_birth}}</td>
							<td><img src="{{$profile->image}}" alt="" class="img-responsive" width="120"></td>
							<td>{{$profile->gender}}</td>
							<td>{{$profile->address}}</td>
							<td>{{$profile->user->name}}</td>
							<td><a href="{{route('profiles.show', $profile->id)}}" class="btn btn-warning btn-sm">Show</a>
								<a href="{{route('profiles.edit', $profile->id)}}" class="btn btn-warning btn-sm">Edit</a>

								<a href="#" onclick="return confirm('are you sure')">
								<form class="pull-right" action="{{route('profiles.destroy', $profile->id)}}" method="POST">
									{{csrf_field()}}
									{{method_field('DELETE')}}
									<button class="btn btn-danger btn-sm" type="submit">Delete</button>
									
								</form>

								</a>

							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
@endsection

projectname/resources/views/profiles/show.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-sm-6 col-sm-offset-3">
				<h1>Profile Details</h1>
				<h3>Name : {{$profile->name}}</h3>
				<img src="{{asset($profile->image)}}" class="img-responsive" alt="">
				<p>Email : {{$profile->email}}</p>
				<p>Date Of Birth : {{$profile->date_of_birth}}</p>
				<p>Gender : {{$profile->gender}}</p>
				<p>Address : {{$profile->address}}</p>
				
			</div>
		</div>
	</div>
@endsection