projectname/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/single', 'HomeController@single');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('profiles', 'ProfileController');
Route::get('/postcategory', [
	'uses' => 'PostCategoryController@index',
	'as' => 'postcategory'
]);


Route::post('/postcategory/store', [
	'uses' => 'PostCategoryController@store',
	'as' => 'postcategory.store'
]);

Route::get('/postcategory/{postcategory}', [
	'uses' => 'PostCategoryController@show',
	'as' => 'postcategory.show'
]);

Route::resource('/posts', 'PostController');

projectname/app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['title', 'description', 'image', 'user_id', 'post_category_id'];
    public function user()
    {
    	return $this->belongsTo('App\User');
    }
    public function post_category()
    {
    	return $this->belongsTo('App\PostCategory');
    }
}

projectname/app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use App\PostCategory;
use Illuminate\Support\Facades\Auth;

class PostController extends Controller
{
    public function __construct(){
        return $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::latest()->get();
        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $postcategories = PostCategory::all();
        return view('posts.create', compact('postcategories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $input = $request->all();
         if($input['image']){
            $input['image'] = $this->upload($request->image);
         }else{
            $input['image'] = 'img/posts/default.jpg';
         }
         $input['user_id'] = Auth::user()->id;
         Post::create($input);
        return redirect('posts');    
    }
    public function upload($file)
        {
            //$extension = $file->getClientOriginalExtension();
            $name = time().$file->getClientOriginalName();
            $filename = $name;
            $current = public_path('img/posts/');
            $file->move($current, $filename);
            return 'img/posts/'.$filename;
        }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

projectname/resources/views/posts/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="row">

		<div class="col-sm-8 col-sm-offset-2">
			<h2>Create Post <a href="{{url('posts')}}" class="btn btn-primary pull-right">Back</a></h2>
			@if(count($errors->all()) > 0)
			<div class="alert alert-warning">
				<ul>
					@foreach($errors->all() as $error)
						<li>{{$error}}</li>
					@endforeach
				</ul>
			</div>
			@endif
			<form action="{{route('posts.store')}}" enctype="multipart/form-data" method="POST">
				{{csrf_field()}}
				<div class="form-group">
					<label for="title">Post Title</label>
					<input type="text" id="title" name="title" class="form-control">
				</div>
				<div class="form-group">
					<label for="image">Select a post Thumbnail</label>
					<input type="file" id="image" name="image" class="form-control">
				</div>
				<div class="form-group">
					<label for="postcategory">Select A Post Category</label>
					<select name="post_category_id" id="postcategory">Select a Post Category
						@foreach($postcategories as $postcategory)
						<option value="{{$postcategory->id}}">{{$postcategory->name}}</option>
						@endforeach
					</select>
				</div>
				<div class="form-group">
					<label for="description">description</label>
					<textarea name="description" id="description" class="form-control" cols="30" rows="5"></textarea>
				</div>
				<button type="submit" class="btn btn-primary">Create</button>
			</form>
		</div>
	</div>
</div>
@endsection
@section('scripts')

@endsection

projectname/resources/views/posts/index.blade.php
@extends('layouts.app')
@section('content')
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				
			<h2>All posts <a href="{{route('posts.create')}}" class="btn btn-success pull-right">Create</a></h2>
		@foreach($posts as $post)
			<div class="single-post" style="margin-bottom: 20px">
				<div class="row">
					<div class="col-sm-5">
						<img class="img-responsive" src="{{asset($post->image)}}" alt="">
					</div>	
					<div class="col-sm-7">
						<h4>{{$post->post_category->name}}</h4>
						<h3>{{$post->title}}</h3>
						<p>{{$post->description}}</p>

						<p><span>Created By : {{$post->user->name}}</span> <span class="pull-right">Created at: {{$post->created_at->toFormattedDateString()}}</span></p>
					</div>	
					
				</div>
			</div>
			@endforeach

			</div>		
		</div>
	</div>
@endsection

projectname/resources/views/posts/postcategory.blade.php
@extends('layouts.app')
@section('content')
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<h3>Post Category List <a href="{{url('postcategory/create')}}" class="btn btn-success pull-right" data-toggle="modal" data-target="#createForm">Create</a></h3>
				<div class="modal fade" id="createForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
				  <div class="modal-dialog" role="document">
				    <div class="modal-content">
				      <div class="modal-header">
				        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				        <h4 class="modal-title" id="myModalLabel">Post Category Create Form</h4>
				      </div>
				      <div class="modal-body">
				       <form action="{{route('postcategory.store')}}" method="POST">
				       	{{csrf_field()}}
				       	<div class="form-group">
				       		<label for="name">Category Name</label>
				       		<input type="text" name="name" id="name" class="form-control">
				       	</div>
				       	<div class="form-group">
				       		<label for="slug">Category Slug</label>
				       		<input type="text" name="slug" id="slug" class="form-control">
				       	</div>
				       	<div class="form-group">
				       		<label for="description">Category Description</label>
				       		<textarea name="description" id="description" cols="30" rows="5" class="form-control"></textarea>
				       	</div>
				       	<button class="btn btn-primary">Create</button>
				       </form>
				      </div>
				      <div class="modal-footer">
				        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				       
				      </div>
				    </div>
				  </div>
				</div>
				<ul>
					@foreach($postcategories as $postcategory)
					<li class="btn btn-default"><a href="{{route('postcategory.show', $postcategory->id)}}">{{$postcategory->name}}</a></li>
					@endforeach
				</ul>
				@if(isset($posts))
				@foreach($posts as $post)
				<div class="single-post" style="margin-bottom: 20px">
					<div class="row">
						<div class="col-sm-5">
							<img class="img-responsive" src="{{asset($post->image)}}" alt="">
						</div>	
						<div class="col-sm-7">
							<h4>{{$post->post_category->name}}</h4>
							<h3>{{$post->title}}</h3>
							<p>{{$post->description}}</p>

							<p><span>Created By : {{$post->user->name}}</span> <span class="pull-right">Created at: {{$post->created_at->toFormattedDateString()}}</span></p>
						</div>	
						
					</div>
				</div>
				@endforeach
				@endif

			</div>
		</div>
	</div>
@endsection